// <auto-generated />
namespace Connect.Default
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class noGender : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(noGender));
        
        string IMigrationMetadata.Id
        {
            get { return "202209230005360_noGender"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
