// <auto-generated />
namespace Connect.DbConnect
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LongerBio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LongerBio));
        
        string IMigrationMetadata.Id
        {
            get { return "202209241855153_LongerBio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
